export const TRAINING_SESSION_ERROR_CODES = {
  FORBIDDEN: "TRAINING_SESSION_FORBIDDEN",
  INVALID_TIME_RANGE: "TRAINING_SESSION_INVALID_TIME_RANGE",
  NOT_FOUND: "TRAINING_SESSION_NOT_FOUND",
} as const;

export type TrainingSessionErrorCode =
  (typeof TRAINING_SESSION_ERROR_CODES)[keyof typeof TRAINING_SESSION_ERROR_CODES];
